name: Rust Manual Build
on:
  workflow_dispatch:    # Only manual trigger
    inputs:
      build_name:
        description: 'Name for the build artifact'
        required: false
        type: string
        default: 'kfc-parser-build'
      branch:          # Added branch selection
        description: 'Branch to build from (e.g., dev)'
        required: true
        type: string
        default: 'dev'

concurrency: production

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}  # Explicitly checkout specified branch
      
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --verbose --release
        
      - name: Run tests
        run: cargo test --verbose
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.build_name || 'kfc-parser-build' }}
          path: target/release/kfc-parser.exe
          retention-days: 90
          if-no-files-found: error
